apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: bgd
  name: bgd
  namespace: user1-todo
spec:
  host: rectangle.apps.cluster-wspf8.wspf8.sandbox961.opentlc.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: bgd
    weight: 100
status: {}
